# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCategory1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_category1(self):
    self.driver.get("http://127.0.0.1:8000/books/category/create/")
    time.sleep(0.5)
    self.driver.maximize_window()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").send_keys("Example")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".submitBtn").click()
    time.sleep(0.5)

  
class TestCategory2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_category2(self):
    self.driver.get("http://127.0.0.1:8000/books/category/create/")
    time.sleep(0.5)
    self.driver.maximize_window()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").send_keys("Category")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_description").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_description").send_keys("A class or division of people or things regarded as having particular shared characteristics.")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".submitBtn").click()
    time.sleep(0.5)


class TestCategory3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_category3(self):
    self.driver.get("http://127.0.0.1:8000/books/category/create/")
    time.sleep(0.5)
    self.driver.maximize_window()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_description").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_description").send_keys("A class or division of people or things regarded as having particular shared characteristics.")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".submitBtn").click()
    time.sleep(4)
