# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAuthor1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_author1(self):
    self.driver.get("http://127.0.0.1:8000/books/author/create/")
    time.sleep(0.5)
    self.driver.maximize_window()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").click()
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_name").send_keys("Mehedi Hasann")
    time.sleep(0.5)
    self.driver.find_element(By.ID, "id_image").send_keys("C:\\Users\\User\\Downloads\\tlp_hero_book-cover-adb8a02f82394b605711f8632a44488b.jpg")
    time.sleep(0.5)
    self.driver.find_element(By.CSS_SELECTOR, ".submitBtn").click()
    time.sleep(0.5)
