import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBook1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_book1(self):
        self.driver.get("http://127.0.0.1:8000/books/add/")
        time.sleep(0.5)
        self.driver.maximize_window()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookName").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookName").send_keys("The Great Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookCover").send_keys("C:\\Users\\User\\Downloads\\tlp_hero_book-cover-adb8a02f82394b605711f8632a44488b.jpg")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "description").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "description").send_keys("The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway\'s interactions with Jay Gatsby, the mysterious millionaire with an obsession to reunite with his former lover, Daisy Buchanan.")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys("Story")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys(Keys.DOWN)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys(Keys.ENTER)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "price").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "price").send_keys("4588")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys("J. K. Rowling")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys(Keys.DOWN)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys(Keys.ENTER)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "rating").click()
        time.sleep(0.5)
        dropdown = self.driver.find_element(By.ID, "rating")
        dropdown.find_element(By.XPATH, "//option[. = '4 stars']").click()
        time.sleep(0.5)
        self.driver.find_element(By.NAME, "suggestions").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "link").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "link").send_keys("https://en.wikipedia.org/wiki/Don_Quixote")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "pages").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "pages").send_keys("999")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "language").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "language").send_keys("English")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "chapters").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "chapters").send_keys("45")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesChapters").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesChapters").send_keys("6")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesQuotes").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesQuotes").send_keys("None")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "series").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "series").send_keys("The Great Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bestCharacter").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bestCharacter").send_keys("Jay Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "awards").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "awards").send_keys("many")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "format").click()
        time.sleep(0.5)
        dropdown = self.driver.find_element(By.ID, "format")
        dropdown.find_element(By.XPATH, "//option[. = 'Paperback']").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(20)").click()
        time.sleep(0.5)
        self.driver.close()



class TestBook2():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_book2(self):
        self.driver.get("http://127.0.0.1:8000/books/add/")
        time.sleep(0.5)
        self.driver.maximize_window()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookName").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookName").send_keys("The Great Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bookCover").send_keys("C:\\Users\\User\\Downloads\\tlp_hero_book-cover-adb8a02f82394b605711f8632a44488b.jpg")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "description").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "description").send_keys("The Great Gatsby is a 1925 novel by American writer F. Scott Fitzgerald. Set in the Jazz Age on Long Island, near New York City, the novel depicts first-person narrator Nick Carraway\'s interactions with Jay Gatsby, the mysterious millionaire with an obsession to reunite with his former lover, Daisy Buchanan.")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys("Story")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys(Keys.DOWN)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "category").send_keys(Keys.ENTER)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "price").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "price").send_keys("4588")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys("J. K. Rowling")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys(Keys.DOWN)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "authors").send_keys(Keys.ENTER)
        time.sleep(0.5)
        self.driver.find_element(By.ID, "rating").click()
        time.sleep(0.5)
        dropdown = self.driver.find_element(By.ID, "rating")
        dropdown.find_element(By.XPATH, "//option[. = '4 stars']").click()
        time.sleep(0.5)
        self.driver.find_element(By.NAME, "suggestions").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "link").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "link").send_keys("https://en.wikipedia.org/wiki/Don_Quixote")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "pages").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "pages").send_keys("999")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "language").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "language").send_keys("English")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "chapters").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "chapters").send_keys("45")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesChapters").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesChapters").send_keys("6")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesQuotes").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "favoritesQuotes").send_keys("None")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "series").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "series").send_keys("The Great Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bestCharacter").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "bestCharacter").send_keys("Jay Gatsby")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "awards").click()
        time.sleep(0.5)
        self.driver.find_element(By.ID, "awards").send_keys("many")
        time.sleep(0.5)
        self.driver.find_element(By.ID, "format").click()
        time.sleep(0.5)
        dropdown = self.driver.find_element(By.ID, "format")
        dropdown.find_element(By.XPATH, "//option[. = 'Paperback']").click()
        time.sleep(0.5)
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(20)").click()
        time.sleep(0.5)
        self.driver.close()
